version: '2'


services:

  web:
    build: .
    image: sandbox/nodejs-bench
    command: node src/index.js
    volumes:
      - ./src:/app/src
    ports:
      - "3000"
    depends_on:
      - redis


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8000:80"


  redis:
    image: redis:alpine